Models/TouristPlace.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Web;

namespace Ex19.Models
{
    public class TouristPlace
    {
        [Key]
        [DatabaseGenerated(DatabaseGeneratedOption.None)]
        public int TouristPlaceId { get; set; }
        [Required]
        public string TouristPlaceName { get; set; }
        [Required]
        public string Description { get; set; }
        [Required]
        public string Location {  get; set; }
        
        public bool Status {  get; set; }
        [Required]
        public string MoreInfo { get; set; }
        
        public string ImagePath { get; set; }
        [NotMapped]
        public HttpPostedFileBase Files { get; set; }
    }
}

Models/TouristPlaceContext.cs
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Web;

namespace Ex19.Models
{
    public class TouristPlaceContext:DbContext
    {
        public TouristPlaceContext()
        {

        }
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            base.OnModelCreating(modelBuilder);
            modelBuilder.Entity<TouristPlace>().ToTable("TouristPlace");
        }
        public DbSet<TouristPlace> tourists { get; set; }
    }
}

Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Ex19.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

Controllers/TouristController.cs
using Ex19.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Ex19.Controllers
{
    public class TouristController : Controller
    {
        TouristPlaceContext dal = null;
        public TouristController()
        {
            dal = new TouristPlaceContext();
        }
        public ActionResult Display()
        {
            List<TouristPlace> tplist = dal.tourists.ToList();
            return View(tplist);
        }

        public ActionResult Index()
        {
            List<TouristPlace> tplist = dal.tourists.ToList();
            return View(tplist);
        }

        public ActionResult AddPlace()
        {
            return View();
        }
        public ActionResult SavePlace(TouristPlace tp)
        {
            
            tp.Files = Request.Files[0];
            tp.ImagePath = "/Images/TouristPlace/" + tp.Files.FileName;
            
            //if (ModelState.IsValid)
            //{
                tp.Files.SaveAs(Server.MapPath(tp.ImagePath));
                dal.tourists.Add(tp);
                dal.SaveChanges();
                return RedirectToAction("Display");
            //}
            //else
            //{
            //    return View("AddPlace", tp);
            //}
            
        }
        public ActionResult EditPlace(int id)
        {
            TouristPlace t = dal.tourists.Find(id);
            return View(t);
        }
        [HttpPost]
        public ActionResult Edit(TouristPlace tp)
        {
            TouristPlace x = dal.tourists.Find(tp.TouristPlaceId);
            x.TouristPlaceId = tp.TouristPlaceId;
            x.TouristPlaceName = tp.TouristPlaceName;
            x.Description = tp.Description;
            x.Location = tp.Location;
            x.MoreInfo = tp.MoreInfo;
            if (Request.Files.Count == 1)
            {
                tp.Files = Request.Files[0];
                tp.ImagePath = "/Images/TouristPlace/" + tp.Files.FileName;
                tp.Files.SaveAs(Server.MapPath(tp.ImagePath));
            }
            dal.tourists.Add(tp);
            dal.SaveChanges();
            return RedirectToAction("Display");
        }   
        public ActionResult Details (int id)
        {
            return View(dal.tourists.Find(id));
        }
        public ActionResult Delete(int id)
        {
            TouristPlace t = dal.tourists.Find(id);
            dal.tourists.Remove(t);
            dal.SaveChanges();
            return RedirectToAction ("Index");
        }

       public ActionResult Employee()
        {
            return View();
        }
    }
}

Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<main aria-labelledby="title">
    <h2 id="title">@ViewBag.Title.</h2>
    <h3>@ViewBag.Message</h3>

    <p>Use this area to provide additional information.</p>
</main>

Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<main aria-labelledby="title">
    <h2 id="title">@ViewBag.Title.</h2>
    <h3>@ViewBag.Message</h3>

    <address>
        One Microsoft Way<br />
        Redmond, WA 98052-6399<br />
        <abbr title="Phone">P:</abbr>
        425.555.0100
    </address>

    <address>
        <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
        <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
    </address>
</main>

Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

<main>
    <section class="row" aria-labelledby="aspnetTitle">
        <h1 id="title">ASP.NET</h1>
        <p class="lead">ASP.NET is a free web framework for building great Web sites and Web applications using HTML, CSS and JavaScript.</p>
        <p><a href="https://asp.net" class="btn btn-primary btn-md">Learn more &raquo;</a></p>
    </section>

    <div class="row">
        <section class="col-md-4" aria-labelledby="gettingStartedTitle">
            <h2 id="gettingStartedTitle">Getting started</h2>
            <p>
                ASP.NET MVC gives you a powerful, patterns-based way to build dynamic websites that
                enables a clean separation of concerns and gives you full control over markup
                for enjoyable, agile development.
            </p>
            <p><a class="btn btn-outline-dark" href="https://go.microsoft.com/fwlink/?LinkId=301865">Learn more &raquo;</a></p>
        </section>
        <section class="col-md-4" aria-labelledby="librariesTitle">
            <h2 id="librariesTitle">Get more libraries</h2>
            <p>NuGet is a free Visual Studio extension that makes it easy to add, remove, and update libraries and tools in Visual Studio projects.</p>
            <p><a class="btn btn-outline-dark" href="https://go.microsoft.com/fwlink/?LinkId=301866">Learn more &raquo;</a></p>
        </section>
        <section class="col-md-4" aria-labelledby="hostingTitle">
            <h2 id="hostingTitle">Web Hosting</h2>
            <p>You can easily find a web hosting company that offers the right mix of features and price for your applications.</p>
            <p><a class="btn btn-outline-dark" href="https://go.microsoft.com/fwlink/?LinkId=301867">Learn more &raquo;</a></p>
        </section>
    </div>
</main>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-dark bg-dark">
        <div class="container">
            @Html.ActionLink("Application name", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            <button type="button" class="navbar-toggler" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" title="Toggle navigation" aria-controls="navbarSupportedContent"
                    aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse d-sm-inline-flex justify-content-between">
                <ul class="navbar-nav flex-grow-1">
                    <li>@Html.ActionLink("Home", "Index", "Home", new { area = "" }, new { @class = "nav-link" })</li>
                    <li>@Html.ActionLink("About", "About", "Home", new { area = "" }, new { @class = "nav-link" })</li>
                    <li>@Html.ActionLink("Contact", "Contact", "Home", new { area = "" }, new { @class = "nav-link" })</li>
                </ul>
            </div>
        </div>
    </nav>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

Views/Tourist/AddPlace.cshtml

@{
    ViewBag.Title = "AddPlace";
}

<h2>Add Place</h2>
<form method="post" action="SavePlace" enctype="multipart/form-data">
<table>
    <tr>
        <th>Tourist Place Id</th>
        <td>
            <input type="text"
                   name="TouristPlaceId"
                   id="TouristPlaceId" />
        </td>
    </tr>
    <tr>
        <th>Name</th>
        <td>
            <input type="text"
                   name="TouristPlaceName"
                   id="TouristPlaceName" />
        </td>
    </tr>
    <tr>
        <th>Description</th>
        <td>
            <textarea name="Description"
                      id="Description"
                      rows="5" cols="150">

            </textarea>
        </td>
    </tr>
    <tr>
        <th>Location</th>
        <td>
            <input type="text"
                   name="Location"
                   id="Location" />
        </td>
    </tr>
    <tr>
        <th>Status</th>
        <td>
            <input type="checkbox"
                   id="Status"
                   name="Status" />
        </td>
    </tr>
    <tr>
        <th>Moreinfo</th>
        <td>
            <input type="text"
                   id="Moreinfo"
                   name="Moreinfo" />
        </td>
    </tr>
    <tr>
        <th>Select Image</th>
        <td>
            <input type="file"
                   name="Files"
                   id="Files" />
        </td>
    </tr>
    <tr>
        <td>
            <input type="reset"
                   value="reset" />
        </td>
        <td>
            <input type="submit"
                   value="Save TouristPlace" />
        </td>
    </tr>

</table>
</form>


Views/Tourist/Details.cshtml
@model Ex19.Models.TouristPlace

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
     <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.TouristPlaceName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.TouristPlaceName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Description)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Description)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Location)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Location)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.MoreInfo)
        </dt>

        <dd>
            <a>@Model.MoreInfo</a>
            @*@Html.DisplayFor(model => model.MoreInfo)*@
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ImagePath)
        </dt>

        <dd>
            <img src="@Model.ImagePath" alt="@Model.TouristPlaceName" width="300" height="150" />
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "EditPlace", new { id = Model.TouristPlaceId }) 
    @Html.ActionLink("Back to List", "Index")
</p>

Views/Tourist/Display.cshtml
@using Ex19.Models
@model List<TouristPlace>
@{
    ViewBag.Title = "SavePlace";
}


<div id="carouselExampleAutoplaying" class="carousel slide" data-bs-ride="carousel">
    <div class="carousel-inner">
        <div class="carousel-item active">
            <img height="420" src="~/Images/TouristPlace/Slide 1.jpg" class="d-block w-100" alt="img">
        </div>
        <div class="carousel-item">
            <img height="420" src="~/Images/TouristPlace/Slide 3.jpg" class="d-block w-100" alt="img">
        </div>
        <div class="carousel-item">

            <img height="420" src="~/Images/TouristPlace/Slide 5.jpg" class="d-block w-100" alt="img">
        </div>
        <div class="carousel-item">
            <img height="420" src="~/Images/TouristPlace/Slide4.jpg" class="d-block w-100" alt="img">
        </div>
        <div class="carousel-item">

            <img height="420" src="~/Images/TouristPlace/Slide 2.jpg" class="d-block w-100" alt="img">
        </div>
    </div>
</div>
<br />
<h2>Top Attractions</h2>

<div class="row row-cols-1 row-cols-md-3 g-4">

    @{
        foreach (TouristPlace tp in Model)
        {
            <div class="col">
                <div class="card h-100">
                    <img src="@Url.Content(tp.ImagePath)" class="card-img-top" alt="@tp.TouristPlaceName">
                    <div class="card-body">
                        <h5 class="card-title">@tp.TouristPlaceName</h5>
                        <p class="card-text">
                            @tp.Description
                        </p>
                    </div>
                    <div class="card-footer">
                        <a class="btn btn-link"
                           href="@tp.MoreInfo"
                           target="_blank">More Info</a>
                    </div>
                </div>
            </div>
        }
    }



</div>


Views/Tourist/EditPlace.cshtml
@model Ex19.Models.TouristPlace

@{
    ViewBag.Title = "EditPlace";
}

<h2>EditPlace</h2>

@using (Html.BeginForm("Edit","Tourist",FormMethod.Post, new {enctype="multipart/form-data"}))
{
    @Html.AntiForgeryToken()
    
<div class="form-horizontal">
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    @Html.HiddenFor(model => model.TouristPlaceId)

    <div class="form-group">
        @Html.LabelFor(model => model.TouristPlaceName, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.TouristPlaceName, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.TouristPlaceName, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Description, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.TextAreaFor(model => model.Description, new { htmlAttributes = new { @class = "form-control" }, rows="9", cols="50" })
            @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
        </div>
    </div>

    @*<div class="form-group">
            <label>Description</label><br />
            <textarea name="Description"
                      id="Description"
                      value="@Model.Description"
                      rows="5" cols="150">
            </textarea>
        </div>*@

    <div class="form-group">
        @Html.LabelFor(model => model.Location, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Location, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Location, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.MoreInfo, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.MoreInfo, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.MoreInfo, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        <label class="control-label col-md-2">Place Image</label>
        <div class="col-md-10">
            <img src="@Model.ImagePath" alt="@Model.TouristPlaceName" width="300" height="150" />
        </div>
    </div>

    <div class="form-group">
        <label class="control-label col-md-2">upload new Image</label>
        <div class="col-md-10">
            <input type="file" id="img" name="img" />
        </div>
    </div>

    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Save" class="btn btn-default" />
        </div>
    </div>
</div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

Views/Tourist/Employee.cshtml

@{
    ViewBag.Title = "Employee";
}

<h2>Employee</h2>
<div >

</div>


Views/Tourist/Index.cshtml
@model IEnumerable<Ex19.Models.TouristPlace>

@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>

<p>
    @Html.ActionLink("Create New", "AddPlace")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.TouristPlaceName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Location)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.MoreInfo)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.ImagePath)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.TouristPlaceName)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Location)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.MoreInfo)
        </td>
        <td>
            <img src="@item.ImagePath" alt="@item.TouristPlaceName" width="300" height="150" />
            @*<img src="@item.ImagePath" alt="img" />*@
        </td>
        <td>
            @Html.ActionLink("Edit", "EditPlace", new { id=item.TouristPlaceId }) |
            @Html.ActionLink("Details", "Details", new { id=item.TouristPlaceId }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.TouristPlaceId })
        </td>
    </tr>
}

</table>